name: AWS Deployment

on:
  push:
    branches: ["master"]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Deploy to EC2
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        EC2_KEY_PAIR: ${{ secrets.EC2_KEY_PAIR }}
        DEPLOY_PATH: /home/ec2-user/portfolio-app
      run: |
          # Install necessary dependencies
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g pm2

          # Clone the repository
          git clone https://github.com/AdleeAfif/portfolio-app.git

          # Install project dependencies
          cd portfolio-app
          npm install

          # Build and start the application in the background
          npm run build
          pm2 start npm --name "portfolio-app" -- start

          # Deploy the application to EC2
          scp $EC2_KEY_PAIR -o StrictHostKeyChecking=no -r portfolio-app/. $EC2_USERNAME@$EC2_PUBLIC_IP:$DEPLOY_PATH
          ssh $EC2_KEY_PAIR -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_IP "cd $DEPLOY_PATH && pm2 restart portfolio-app"
