name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Set up Git user identity
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME

      - run: npm i
      - run: npm run build --if-present
      - run: npm run deploy
    # - run: npm test --passWithNoTests
    # git remote set-url origin https://$MY_NAME:${{ secrets.MY_PASSWORD }}@github.com/AdleeAfif/portfolio-app.git
