name: Node.js CI

on:
  push:
    branches: ["master"]

env:
  MY_NAME: ${{ vars.MY_NAME }}
  MY_EMAIL: ${{ vars.MY_EMAIL }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [19.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
        
    - name: Set up Git user identity
      run: |
        git config --global user.email $MY_EMAIL
        git config --global user.name $MY_NAME
        git remote set-url origin https://${{ secrets.MY_TOKEN }}@github.com/AdleeAfif/portfolio-app.git
        
    - run: npm i
    - name: Set public URL
      run: |
        echo "PUBLIC_URL=https://nikadlee.dev" >> $GITHUB_OUTPUT
    - run: npm run build --if-present
    - name: Create CNAME file
      run: echo "nikadlee.dev" > ./build/CNAME
    - run: npm run deploy
